In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math

In [2]:
wind = pd.read_csv('wind_speed.csv')
wind

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,1/1/2012 0:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,1/1/2012 1:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,1/1/2012 2:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,1/1/2012 3:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,1/1/2012 4:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,12/31/2012 19:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,12/31/2012 20:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,12/31/2012 21:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,12/31/2012 22:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,12/31/2012 23:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [3]:
wind.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   object
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: float64(4), int64(2), object(2)
memory usage: 549.1+ KB

In [4]:
wind['Date/Time'] = pd.to_datetime(wind['Date/Time'])

In [5]:
wind.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Date/Time         8784 non-null   datetime64[ns]
 1   Temp_C            8784 non-null   float64
 2   Dew Point Temp_C  8784 non-null   float64
 3   Rel Hum_%         8784 non-null   int64
 4   Wind Speed_km/h   8784 non-null   int64
 5   Visibility_km     8784 non-null   float64
 6   Press_kPa         8784 non-null   float64
 7   Weather           8784 non-null   object
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB

In [6]:
wind

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
2,2012-01-01 02:00:00,-1.8,-3.4,89,7,4.0,101.26,"Freezing Drizzle,Fog"
3,2012-01-01 03:00:00,-1.5,-3.2,88,6,4.0,101.27,"Freezing Drizzle,Fog"
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

# QUESTION 

Q. 1)  Find all the unique 'Wind Speed' values in the data.
    
Q. 2) Find the number of times when the 'Weather is exactly Clear'.

Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'.
    
Q. 4) Find out all the Null Values in the data.
    
Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.

Q. 6) What is the mean 'Visibility' ?

Q. 7) What is the Standard Deviation of 'Pressure'  in this data?

Q. 8) What is the Variance of 'Relative Humidity' in this data ?

Q. 9) Find all instances when 'Snow' was recorded.

Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.

Q. 11) What is the Mean value of each column against each 'Weather Condition ?

Q. 12) What is the Minimum & Maximum value of each column against each 'Weather Condition ?


Q. 13) Show all the Records where Weather Condition is Fog.

Q. 14) Fin#d all instances when 'Weather is Clear' or 'Visibility is above 40'.

Q. 15) Find all instances when :

A. 'Weather is Clear' and 'Relative Humidity is greater than 50'

or
B. 'Visibility is above 40'

In [7]:
# Q. 1) Find all the unique 'Wind Speed' values in the data.
wind['Wind Speed_km/h'].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2],
      dtype=int64)

In [8]:
# Q. 2) Find the number of times when the 'Weather is exactly Clear'. 
wind[wind['Weather'] == 'Clear'].shape[0]

1326

In [9]:
# Q. 3) Find the number of times when the 'Wind Speed was exactly 4 km/h'. 
wind[wind['Wind Speed_km/h'] == 4].shape[0]

474

In [10]:
# Q. 4) Find out all the Null Values in the data. 
wind.isnull().sum()

Date/Time           0
Temp_C              0
Dew Point Temp_C    0
Rel Hum_%           0
Wind Speed_km/h     0
Visibility_km       0
Press_kPa           0
Weather             0
dtype: int64

In [11]:
# Q. 5) Rename the column name 'Weather' of the dataframe to 'Weather Condition'.
wind.rename(columns = {'Weather' : 'Weather Condition'} ,inplace = True)

In [12]:
wind.columns

Index(['Date/Time', 'Temp_C', 'Dew Point Temp_C', 'Rel Hum_%',
       'Wind Speed_km/h', 'Visibility_km', 'Press_kPa', 'Weather Condition'],
      dtype='object')

In [13]:
# Q. 6) What is the mean 'Visibility' ? 
numerator = wind['Visibility_km'].sum()
denomintor = wind['Visibility_km'].count()
print(numerator / denomintor)

27.664446721311478

In [14]:
# Q. 7) What is the Standard Deviation of 'Pressure'  in this data? 
mean = wind['Press_kPa'].mean()
num = ((wind['Press_kPa'] - mean) ** 2).sum()
deno = wind['Press_kPa'].count() - 1

s = math.sqrt(num / deno)
print("Standard Deviation of Pressure:", s)

Standard Deviation of Pressure: 0.8440047459486483

In [15]:
#  Q. 8) What is the Variance of 'Relative Humidity' in this data ?

mean = wind['Press_kPa'].mean()
num = ((wind['Press_kPa'] - mean) ** 2).sum()
deno = wind['Press_kPa'].count() - 1

s = math.sqrt(num / deno)
print("Standard Deviation of Pressure:", s**2)

Standard Deviation of Pressure: 0.7123440111838423

In [16]:
# Q. 9) Find all instances when 'Snow' was recorded.
wind[wind['Weather Condition'] == 'Snow']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
55,2012-01-03 07:00:00,-14.0,-19.5,63,19,25.0,100.95,Snow
84,2012-01-04 12:00:00,-13.7,-21.7,51,11,24.1,101.25,Snow
86,2012-01-04 14:00:00,-11.3,-19.0,53,7,19.3,100.97,Snow
87,2012-01-04 15:00:00,-10.2,-16.3,61,11,9.7,100.89,Snow
88,2012-01-04 16:00:00,-9.4,-15.5,61,13,19.3,100.79,Snow
...,...,...,...,...,...,...,...,...
8779,2012-12-31 19:00:00,0.1,-2.7,81,30,9.7,100.13,Snow
8780,2012-12-31 20:00:00,0.2,-2.4,83,24,9.7,100.03,Snow
8781,2012-12-31 21:00:00,-0.5,-1.5,93,28,4.8,99.95,Snow
8782,2012-12-31 22:00:00,-0.2,-1.8,89,28,9.7,99.91,Snow
8783,2012-12-31 23:00:00,0.0,-2.1,86,30,11.3,99.89,Snow

In [17]:
# Q. 10) Find all instances when 'Wind Speed is above 24' and 'Visibility is 25'.
wind[(wind['Wind Speed_km/h'] >= 24) & (wind['Visibility_km'] == 25)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
23,2012-01-01 23:00:00,5.3,2.0,79,30,25.0,99.31,Cloudy
24,2012-01-02 00:00:00,5.2,1.5,77,35,25.0,99.26,Rain Showers
25,2012-01-02 01:00:00,4.6,0.0,72,39,25.0,99.26,Cloudy
26,2012-01-02 02:00:00,3.9,-0.9,71,32,25.0,99.26,Mostly Cloudy
27,2012-01-02 03:00:00,3.7,-1.5,69,33,25.0,99.30,Mostly Cloudy
...,...,...,...,...,...,...,...,...
8754,2012-12-30 18:00:00,-12.6,-16.0,76,24,25.0,101.36,Mainly Clear
8755,2012-12-30 19:00:00,-13.4,-16.5,77,26,25.0,101.47,Mainly Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear
8759,2012-12-30 23:00:00,-12.1,-15.1,78,28,25.0,101.52,Mostly Cloudy
8760,2012-12-31 00:00:00,-11.1,-14.4,77,26,25.0,101.51,Cloudy

In [18]:
# Q. 11) What is the Mean value of each column against each 'Weather Condition ?
wind.groupby('Weather Condition').mean().head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,2012-06-25 18:03:12.760180992,6.825716,0.089367,64.497738,10.557315,30.153243,101.587443
Cloudy,2012-07-01 16:51:29.583333376,7.970544,2.375810,69.592593,16.127315,26.625752,100.911441
Drizzle,2012-09-17 15:00:00.000000000,7.353659,5.504878,88.243902,16.097561,17.931707,100.435366
"Drizzle,Fog",2012-06-30 00:44:15.000000000,8.067500,7.033750,93.275000,11.862500,5.257500,100.786625
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00.000000000,0.400000,-0.700000,92.000000,20.000000,4.000000,100.790000

In [19]:
# Q. 12) What is the Minimum & Maximum value of each column against each 'Weather Condition ? 
wind.groupby('Weather Condition').min().head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,2012-01-03 19:00:00,-23.3,-28.5,20,0,11.3,99.52
Cloudy,2012-01-01 17:00:00,-21.4,-26.8,18,0,11.3,98.39
Drizzle,2012-01-23 21:00:00,1.1,-0.2,74,0,6.4,97.84
"Drizzle,Fog",2012-01-23 20:00:00,0.0,-1.6,85,0,1.0,98.65
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00,0.4,-0.7,92,20,4.0,100.79

In [20]:
wind.groupby('Weather Condition').max().head()

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa
Weather Condition,,,,,,,
Clear,2012-12-30 20:00:00,32.8,20.4,99,33,48.3,103.63
Cloudy,2012-12-31 06:00:00,30.5,22.6,99,54,48.3,103.65
Drizzle,2012-12-22 01:00:00,18.8,17.7,96,30,25.0,101.56
"Drizzle,Fog",2012-12-19 10:00:00,19.9,19.1,100,28,9.7,102.07
"Drizzle,Ice Pellets,Fog",2012-12-17 09:00:00,0.4,-0.7,92,20,4.0,100.79

In [22]:
# Q. 13) Show all the Records where Weather Condition is Fog.
wind[wind['Weather Condition'] == 'Fog']

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
0,2012-01-01 00:00:00,-1.8,-3.9,86,4,8.0,101.24,Fog
1,2012-01-01 01:00:00,-1.8,-3.7,87,4,8.0,101.24,Fog
4,2012-01-01 04:00:00,-1.5,-3.3,88,7,4.8,101.23,Fog
5,2012-01-01 05:00:00,-1.4,-3.3,87,9,6.4,101.27,Fog
6,2012-01-01 06:00:00,-1.5,-3.1,89,7,6.4,101.29,Fog
...,...,...,...,...,...,...,...,...
8716,2012-12-29 04:00:00,-16.0,-17.2,90,6,9.7,101.25,Fog
8717,2012-12-29 05:00:00,-14.8,-15.9,91,4,6.4,101.25,Fog
8718,2012-12-29 06:00:00,-13.8,-15.3,88,4,9.7,101.25,Fog
8719,2012-12-29 07:00:00,-14.8,-16.4,88,7,8.0,101.22,Fog
8722,2012-12-29 10:00:00,-12.0,-13.3,90,7,6.4,101.15,Fog

In [24]:
# Q. 14) Find all instances when 'Weather is Clear' or 'Visibility is above 40'.
wind[(wind['Weather Condition'] == 'Clear') &(wind['Visibility_km'] >40)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
351,2012-01-15 15:00:00,-15.4,-22.8,53,24,48.3,102.71,Clear
352,2012-01-15 16:00:00,-15.1,-22.8,52,24,48.3,102.79,Clear
425,2012-01-18 17:00:00,-11.3,-18.8,54,26,48.3,101.54,Clear
440,2012-01-19 08:00:00,-13.7,-18.4,68,19,48.3,101.84,Clear
441,2012-01-19 09:00:00,-12.7,-17.2,69,17,48.3,101.73,Clear
...,...,...,...,...,...,...,...,...
8384,2012-12-15 08:00:00,-10.7,-15.6,67,13,48.3,102.69,Clear
8385,2012-12-15 09:00:00,-10.4,-15.9,64,19,48.3,102.74,Clear
8389,2012-12-15 13:00:00,-8.4,-14.7,60,19,48.3,102.64,Clear
8631,2012-12-25 15:00:00,-7.1,-13.7,59,17,48.3,101.98,Clear
8632,2012-12-25 16:00:00,-7.5,-13.9,60,11,48.3,102.03,Clear

In [ ]:
# Q. 15) Find all instances when :

# A. 'Weather is Clear' and 'Relative Humidity is greater than 50'

# or B. 'Visibility is above 40'

In [25]:
wind[(wind['Weather Condition'] == 'Clear') & (wind['Rel Hum_%'] >50)]

,Date/Time,Temp_C,Dew Point Temp_C,Rel Hum_%,Wind Speed_km/h,Visibility_km,Press_kPa,Weather Condition
114,2012-01-05 18:00:00,-7.1,-14.4,56,11,25.0,100.71,Clear
115,2012-01-05 19:00:00,-9.2,-15.4,61,7,25.0,100.80,Clear
116,2012-01-05 20:00:00,-9.8,-15.7,62,9,25.0,100.83,Clear
117,2012-01-05 21:00:00,-9.0,-14.8,63,13,25.0,100.83,Clear
241,2012-01-11 01:00:00,-10.7,-17.8,56,17,25.0,101.49,Clear
...,...,...,...,...,...,...,...,...
8646,2012-12-26 06:00:00,-13.4,-14.8,89,4,25.0,102.47,Clear
8698,2012-12-28 10:00:00,-6.1,-8.6,82,19,24.1,101.27,Clear
8713,2012-12-29 01:00:00,-11.9,-13.6,87,11,25.0,101.31,Clear
8714,2012-12-29 02:00:00,-11.8,-13.1,90,13,25.0,101.33,Clear
8756,2012-12-30 20:00:00,-13.8,-16.5,80,24,25.0,101.52,Clear